version: '3.7'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - FRONTEND_ASSET_PATH=/assets
      - PORT=3030
    command: npx nodemon ./src/server.js
    volumes:
      - ./backend/src:/app/src
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
  nginx:
    image: nginx
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command: nginx -g 'daemon off;'
    depends_on:
      - server
      - frontend
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot